easy_admin:
    entities:
        # List the entity class name you want to manage
        Identity:
            class: App\Entity\Identity
            list:
                fields:
                    - 'id'
                    - { property: 'description', label: 'Ma Description' }
                    - { property: 'backgroundimg', type: 'image', base_path: '%app.path.identity_images%', label: 'Image Bannière' }
                    - { property: 'profileimg', type: 'image', base_path: '%app.path.identity_images%', label: 'Image Profil' }
            new:
                fields:
                    - { property: 'description', label: 'Ma Description' }
                    - { type: 'divider' }
                    - { property: 'backgroundimg', type: 'file', label: 'Image Bannière' }
                    - { property: 'profileimg', type: 'file', label: 'Image Profil' }
                    - { type: 'divider' }
            edit:
                fields:
                    - { property: 'description', label: 'Ma Description' }
                    - { type: 'divider' }
                    - { property: 'backgroundimgFile', type: 'file', label: 'Image Bannière' }
                    - { property: 'profileimgFile', type: 'file', label: 'Image Profil' }
                    - { type: 'divider' }

        Project:
            class: App\Entity\Project
            list:
                fields:
                    - 'id'
                    - { property: 'projecttitle', label: 'Nom du Projet' }
                    - { property: 'projectdescription', label: 'Description' }
                    - { property: 'projectimg', type: 'image', base_path: '%app.path.project_images%', label: 'Image du Projet' }
            new:
                fields:
                    - { property: 'projecttitle', label: 'Nom du Projet' }
                    - { type: 'divider' }
                    - { property: 'projectdescription', label: 'Description' }
                    - { property: 'projectimg', type: 'file', label: 'Image du Projet' }
                    - { type: 'divider' }
            edit:
                fields:
                    - { property: 'projecttitle', label: 'Nom du Projet' }
                    - { type: 'divider' }
                    - { property: 'projectdescription', label: 'Description' }
                    - { property: 'projectimgFile', type: 'file', label: 'Image du Projet' }
                    - { type: 'divider' }

        Topicality:
            class: App\Entity\Topicality

    design:
        form_theme: 'vertical'
        menu:
            - { entity: 'Identity', label: 'Page Accueil' }
            - { entity: 'Project', label: 'Page Projets' }
            - { entity: 'Topicality', label: 'Page Actualités' }
        brand_color: '#0e1c37'
        templates:
            edit: '@App/Backend/layout.html.twig'
        color_scheme: 'light'

    site_name: 'Gestion du Site'
