vich_uploader:
    db_driver: orm

    mappings:
        identity:
            uri_prefix: '%app.path.identity_images%'
            upload_destination: '%kernel.project_dir%/public/uploads/images/identity'
        project:
            uri_prefix: '%app.path.project_images%'
            upload_destination: '%kernel.project_dir%/public/uploads/images/project'